project:
  type: website
  output-dir: docs

website:
  announcement:
    icon: info-circle
    dismissable: false
    content: "This website is currently under development! Updates are likely to continue until EDS 296 begins in Fall 2024."
  title: "EDS 296"
  navbar:
    right:
      - href: index.qmd
        text: home
      - text: syllabus
        href: https://docs.google.com/document/d/1FOpQ_0x8JCbJ6-U0TPsy4WeVPeYL4PIvDzaOUyDN-Vg/edit?usp=sharing
        target: _blank
      - text: course materials
        menu:
          - text: week 0 (9/27) 
            href: course-materials/week0-build-websites.qmd
          - text: week 2 (10/11) 
            href: course-materials/week2-customizing-websites.qmd
          - text: week 3 (10/18)
            href: course-materials/week3-creating-blogs.qmd
          - text: week 4 (10/25) 
            href: course-materials/week4-writing-blogs.qmd
          - text: week 5 (11/1)
            href: course-materials/week5-github-portfolios.qmd
          - text: week 6 (11/8)
            href: course-materials/week6-misc-github.qmd
      - text: resources
        menu: 
          - text: guide for writing clean code
            href: clean-code-guide.qmd
          - text: MEDS installation guide
            href: https://ucsb-meds.github.io/MEDS-installation-guide/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/samanthacsik/eds296-DS-portfolios
          - text: Report a Bug
            url:  https://github.com/samanthacsik/eds296-DS-portfolios/issues
  page-footer:
    background: dark
    right: This website is built with [{{< fa brands github title="the github octocat logo" >}}](https://github.com/samanthacsik/EDS-240-data-viz), [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html) and [Quarto](https://quarto.org/)
    # center: |
    #   <img src="images/bren-logo.png" alt="The Bren School of Environmental Science & Management logo" width="250"/>
    left: This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

format:
  html:
    theme: meds-website-styles.scss
    toc: false
    page-layout: full
    code-line-numbers: true


