---
title: "Writing blogs"
format: revealjs
---

## title slide

---

## TL;DR

HT: Julie Lowndes

---

<https://docs.google.com/presentation/d/1dxviUquj4xTNY5pzoGSL-pukWgqC_nPqM9jCemiRAuY/edit#slide=id.g20e7ef3cb4c_0_365>

---

- have them read 2 posts in class and highlight what they do or don't like about them in class; can think about tone, framing, humor, illustrations/visuals (what did they add/subtract); writing is subjective!
- have a draft outline of a blog post; by end of course, there should a fully finished blog; can amplify on social media

---

- storytelling -- core pieces + embellishments (e.g. humor;j should add some but don't have to add all of them)
- rescue was usign a super frustrating fxn but then found a new bettter one!
- can break the rules; should have a story but not all of it has to be a part of the story necessarily
- read some curated SECTIONS of blog posts and discuss things like tone, audience, humor, visuals (things they liked/didnt like as both a reader and a writer
- draft an outline of their blog post in class and maybe exchange with someone for thoughts

